project_id = "epwriqkyqxwewwcxbnsu"

[functions.generate-review-response]
verify_jwt = true

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[functions.sync-reviews]
verify_jwt = true

[functions.oauth-callback]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true