// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epwriqkyqxwewwcxbnsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwd3JpcWt5cXh3ZXd3Y3hibnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Mjk0MTcsImV4cCI6MjA2OTMwNTQxN30.2rfz-G6FlCRtDMT8-Ws3V06ngQPpwRV8xpVCrT8MQ0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});